### ISSUE TITLE
PCE duplicates parameters for first segment in computed path

### ISSUE THREAD

**Issue by erikrozendaal** [BandwidthOnDemand/nsi-pce#19]
When we ask the PCE to compute a path that results in multiple segments the Point2Point parameters are duplicated in the first segment. This does not occur when the computed path consists of only a single segment.

Example request:
```json
{
  "correlationId" : "urn:uuid:ddb541d3-95fa-4119-8a09-8a10a7aec749",
  "replyTo" : {
    "url" : "https://safnari.acc.dlp.surfnet.nl/pce/reply",
    "mediaType" : "application/json"
  },
  "algorithm" : "SEQUENTIAL",
  "constraints" : [ ],
  "serviceType" : "http://services.ogf.org/nsi/2013/12/descriptions/EVTS.A-GOLE",
  "p.p2ps" : [ {
    "capacity" : 5,
    "directionality" : "Bidirectional",
    "symmetricPath" : true,
    "sourceSTP" : "urn:ogf:network:netherlight.net:2013:topology:manlan-2?vlan=100",
    "destSTP" : "urn:ogf:network:surfnet.nl:1990:testbed7:26026?vlan=100",
    "parameter" : [ {
      "@type" : "protection",
      "value" : "PROTECTED"
    }, {
      "@type" : "pathComputationAlgorithm",
      "value" : "SEQUENTIAL"
    } ]
  } ],
  "trace" : [ ]
}
```

results in

```json
{
  "correlationId" : "urn:uuid:ddb541d3-95fa-4119-8a09-8a10a7aec749",
  "status" : "SUCCESS",
  "path" : [ {
    "nsa" : "urn:ogf:network:netherlight.net:2013:nsa:netherlight-acc",
    "csProviderURL" : "https://netherlight.acc.dlp.surfnet.nl/nsi/v2/provider",
    "serviceType" : "http://services.ogf.org/nsi/2013/12/descriptions/EVTS.A-GOLE",
    "p.p2ps" : [ {
      "capacity" : 5,
      "directionality" : "Bidirectional",
      "symmetricPath" : true,
      "sourceSTP" : "urn:ogf:network:netherlight.net:2013:topology:manlan-2?vlan=100",
      "destSTP" : "urn:ogf:network:netherlight.net:2013:topology:surfnet-1?vlan=200-299",
      "parameter" : [ {
        "@type" : "protection",
        "value" : "PROTECTED"
      }, {
        "@type" : "pathComputationAlgorithm",
        "value" : "SEQUENTIAL"
      }, {
        "@type" : "protection",
        "value" : "PROTECTED"
      }, {
        "@type" : "pathComputationAlgorithm",
        "value" : "SEQUENTIAL"
      } ]
    } ]
  }, {
    "nsa" : "urn:ogf:network:surfnet.nl:1990:nsa:bod-acc",
    "csProviderURL" : "https://bod.acc.dlp.surfnet.nl/nsi/v2/provider",
    "serviceType" : "http://services.ogf.org/nsi/2013/12/descriptions/EVTS.A-GOLE",
    "p.p2ps" : [ {
      "capacity" : 5,
      "directionality" : "Bidirectional",
      "symmetricPath" : true,
      "sourceSTP" : "urn:ogf:network:surfnet.nl:1990:testbed7:netherlight-1?vlan=200-299",
      "destSTP" : "urn:ogf:network:surfnet.nl:1990:testbed7:26026?vlan=100",
      "parameter" : [ {
        "@type" : "protection",
        "value" : "PROTECTED"
      }, {
        "@type" : "pathComputationAlgorithm",
        "value" : "SEQUENTIAL"
      } ]
    } ]
  } ]
}
```

**Comment by jmacauley** [comment]
What is the function of:

      "@type" : "pathComputationAlgorithm",
      "value" : "SEQUENTIAL"

Is this strictly used so you can remember the type of path finding algorithm you used?

**Comment by erikrozendaal** [comment]
We use this parameter to allow the NSI requester and BoD to specify the path computation algorithm to use (chain, tree, sequential). It is passed in the NSI initial reserve request headers (just like the `protection` parameter) and these are currently passed "as-is" to the PCE.

**Comment by jmacauley** [comment]
Could you verify this isn't safnari adding parameters back into the response?  I discussed this problem with Alan and I can't remember if it was solved.  I have added test cases to match your input parameters but cannot reproduce the issue.  Here is one of the 17 different path requests performed in my test case.  Each is done once with TREE and once with SEQUENTIAL algorithms:

    {
        "correlationId": "80eab8fd-dc19-4507-b71b-84b1f83bc754",
        "replyTo": {
            "url": "http://localhost:8401/aggregator/path",
            "mediaType": "application/json"
        },
        "algorithm": "SEQUENTIAL",
        "startTime": "2016-11-17T23:19:40.085Z",
        "endTime": "2016-11-17T23:29:40.085Z",
        "serviceType": "http://services.ogf.org/nsi/2013/12/descriptions/EVTS.A-GOLE",
        "trace": [
            {
                "@index": 2,
                "value": "urn:ogf:network:surfnet.nl:1990:nsa:bod-acc"
            },
            {
                "@index": 5,
                "value": "urn:ogf:network:sinet.ac.jp:2013:nsa"
            },
            {
                "@index": 3,
                "value": "urn:ogf:network:aist.go.jp:2013:nsa"
            },
            {
                "@index": 4,
                "value": "urn:ogf:network:pionier.net.pl:2013:nsa"
            },
            {
                "@index": 1,
                "value": "urn:ogf:network:geant.net:2013:nsa"
            }
        ],
        "p.p2ps": [{
            "capacity": 100,
            "directionality": "Bidirectional",
            "symmetricPath": true,
            "sourceSTP": "urn:ogf:network:kddilabs.jp:2013:topology:bi-ps?vlan=1780-1790",
            "destSTP": "urn:ogf:network:uvalight.net:2013:topology:ps?vlan=1780-1790",
            "ero": {"orderedSTP": [{
                "@order": 0,
                "stp": "urn:ogf:network:icair.org:2013:topology:netherlight?vlan=1780-1790"
            }]},
            "parameter": [
                {
                    "@type": "protection",
                    "value": "PROTECTED"
                },
                {
                    "@type": "pathComputationAlgorithm",
                    "value": "SEQUENTIAL"
                }
            ]
        }]
    }

Here is the expected response with only one copy of the parameters:

    {
        "correlationId": "80eab8fd-dc19-4507-b71b-84b1f83bc754",
        "status": "SUCCESS",
        "path": [
            {
                "nsa": "urn:ogf:network:netherlight.net:2013:nsa:safnari",
                "csProviderURL": "https://agg.netherlight.net/nsi-v2/ConnectionServiceProvider",
                "serviceType": "http://services.ogf.org/nsi/2013/12/descriptions/EVTS.A-GOLE",
                "p.p2ps": [{
                    "capacity": 100,
                    "directionality": "Bidirectional",
                    "symmetricPath": true,
                    "sourceSTP": "urn:ogf:network:kddilabs.jp:2013:topology:bi-ps?vlan=1780-1790",
                    "destSTP": "urn:ogf:network:kddilabs.jp:2013:topology:bi-kddilabs-jgn-x?vlan=1781",
                    "parameter": [
                        {
                            "@type": "protection",
                            "value": "PROTECTED"
                        },
                        {
                            "@type": "pathComputationAlgorithm",
                            "value": "SEQUENTIAL"
                        }
                    ]
                }]
            },
            {
                "nsa": "urn:ogf:network:netherlight.net:2013:nsa:safnari",
                "csProviderURL": "https://agg.netherlight.net/nsi-v2/ConnectionServiceProvider",
                "serviceType": "http://services.ogf.org/nsi/2013/12/descriptions/EVTS.A-GOLE",
                "p.p2ps": [{
                    "capacity": 100,
                    "directionality": "Bidirectional",
                    "symmetricPath": true,
                    "sourceSTP": "urn:ogf:network:jgn-x.jp:2013:topology:bi-jgn-x-kddilabs?vlan=1781",
                    "destSTP": "urn:ogf:network:jgn-x.jp:2013:topology:bi-jgn-x-startap?vlan=1781",
                    "parameter": [
                        {
                            "@type": "protection",
                            "value": "PROTECTED"
                        },
                        {
                            "@type": "pathComputationAlgorithm",
                            "value": "SEQUENTIAL"
                        }
                    ]
                }]
            },
            {
                "nsa": "urn:ogf:network:icair.org:2013:nsa",
                "csProviderURL": "https://pmri061.it.northwestern.edu:9443/NSI/services/CS2",
                "serviceType": "http://services.ogf.org/nsi/2013/12/descriptions/EVTS.A-GOLE",
                "p.p2ps": [{
                    "capacity": 100,
                    "directionality": "Bidirectional",
                    "symmetricPath": true,
                    "sourceSTP": "urn:ogf:network:icair.org:2013:topology:jgn-x?vlan=1781",
                    "destSTP": "urn:ogf:network:icair.org:2013:topology:netherlight?vlan=1781",
                    "parameter": [
                        {
                            "@type": "protection",
                            "value": "PROTECTED"
                        },
                        {
                            "@type": "pathComputationAlgorithm",
                            "value": "SEQUENTIAL"
                        }
                    ]
                }]
            },
            {
                "nsa": "urn:ogf:network:netherlight.net:2013:nsa:safnari",
                "csProviderURL": "https://agg.netherlight.net/nsi-v2/ConnectionServiceProvider",
                "serviceType": "http://services.ogf.org/nsi/2013/12/descriptions/EVTS.A-GOLE",
                "p.p2ps": [{
                    "capacity": 100,
                    "directionality": "Bidirectional",
                    "symmetricPath": true,
                    "sourceSTP": "urn:ogf:network:netherlight.net:2013:production7:starlight-1?vlan=1781",
                    "destSTP": "urn:ogf:network:netherlight.net:2013:production7:uva-3?vlan=1780",
                    "parameter": [
                        {
                            "@type": "protection",
                            "value": "PROTECTED"
                        },
                        {
                            "@type": "pathComputationAlgorithm",
                            "value": "SEQUENTIAL"
                        }
                    ]
                }]
            },
            {
                "nsa": "urn:ogf:network:netherlight.net:2013:nsa:safnari",
                "csProviderURL": "https://agg.netherlight.net/nsi-v2/ConnectionServiceProvider",
                "serviceType": "http://services.ogf.org/nsi/2013/12/descriptions/EVTS.A-GOLE",
                "p.p2ps": [{
                    "capacity": 100,
                    "directionality": "Bidirectional",
                    "symmetricPath": true,
                    "sourceSTP": "urn:ogf:network:uvalight.net:2013:topology:netherlight?vlan=1780",
                    "destSTP": "urn:ogf:network:uvalight.net:2013:topology:ps?vlan=1780-1790",
                    "parameter": [
                        {
                            "@type": "protection",
                            "value": "PROTECTED"
                        },
                        {
                            "@type": "pathComputationAlgorithm",
                            "value": "SEQUENTIAL"
                        }
                    ]
                }]
            }
        ]
    }

**Comment by erikrozendaal** [comment]
This was indeed caused by Safnari accidentally mutating a Java/JAXB object 😞
